---
- name: Create New AD User
  hosts: HMIAMDC02
  gather_facts: no

  # O prompt só aparece se você rodar via terminal. 
  # No AWX, o Survey preenche essas variáveis automaticamente.
  vars_prompt:
    - name: target_user
      prompt: "Username do logon"
      private: no
    - name: first_name
      prompt: "Primeiro nome"
      private: no
    - name: last_name
      prompt: "Sobrenome"
      private: no
    - name: new_password
      prompt: "Senha inicial"
      private: yes
    - name: ou_path
      prompt: "Caminho da OU"
      private: no

  vars:
    domain_name: "hmic.ao" # Ajuste para o seu domínio

  tasks:
    - name: Criar o novo usuário no AD com todos os campos
      microsoft.ad.user:
        identity: "{{ target_user }}"
        state: present
        name: "{{ first_name }} {{ last_name }}"
        firstname: "{{ first_name }}"
        surname: "{{ last_name }}"
        display_name: "{{ first_name }} {{ last_name }}"
        upn: "{{ target_user }}@{{ domain_name }}"
        sam_account_name: "{{ target_user }}"
        path: "{{ ou_path }}"
        password: "{{ new_password }}"
        enabled: yes
        password_expired: yes
