---
- name: Atualizar servidores Windows
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Instalar atualizações
      win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
      register: update_result

    - name: Reiniciar se necessário
      win_reboot:
      when: update_result.reboot_required

    - name: Esperar que o servidor esteja de volta
      wait_for:
        port: 5985
        timeout: 600
      when: update_result.reboot_required

