---
- name: Configure Microsoft Defender
  hosts: windows

  tasks:
    - name: Enable real-time protection
      ansible.windows.win_regedit:
        path: HKLM:\Software\Microsoft\Windows Defender\Real-Time Protection
        name: DisableRealtimeMonitoring
        data: 0
        type: dword

    - name: Configure Defender Cloud Protection
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows Defender\Spynet
        name: SpynetReporting
        data: 2
        type: dword

