---
- name: Resetar senha de usuário do AD
  hosts: 10.10.203.6
  gather_facts: no

  vars:
    name: "target_username"
    prompt: "Digite o nome de usuário para resetar"
    private: no

    name: "new_password"
    prompt: "Digite a nova senha temporária"
    private: yes

  tasks:

    - name: Check if the target user exists and reset password
      ansible.windows.win_domain_user:
        name: "{{ target_username }}"
        state: present

        password: "{{ new_password }}"
        # Define a senha para expirar, forçando o usuário a trocá-la no próximo logon
        password_never_expires: no
        password_not_changeable: no
        password_expires: yes
        
      delegate_to: "{{ inventory_hostname }}"
      register: result

    - name: Inform the support user that the reset was successful
      ansible.builtin.debug:
        msg: "Senha do usuário '{{ target_username }}' resetada com sucesso. O usuário será forçado a trocar a senha no próximo logon."
