---
- name: Reset AD User Password
  hosts: AD
  gather_facts: no

  vars_prompt:
    - name: target_user
      prompt: "Digite o username do AD a resetar (ex: d.garcia)"
      private: no

    - name: new_password
      prompt: "Digite a nova senha"
      private: yes

  tasks:

    - name: Verificar se o usuário existe no AD
      microsoft.ad.user:
        name: "{{ target_user }}"
        state: query
      register: user_check
      failed_when: false   # NÃO falha aqui
      changed_when: false

    - name: Exibir erro amigável se o usuário não existir
      when: user_check.found is not defined or user_check.found == 0
      fail:
        msg:
          - "O usuário '{{ target_user }}' NÃO foi encontrado no Active Directory."
          - "➡ Verifique se o nome está correto."
          - "➡ Exemplo válido: d.garcia"

    - name: Reset password para o usuário {{ target_user }}
      microsoft.ad.user:
        name: "{{ target_user }}"
        password: "{{ new_password }}"
        update_password: always
        state: present
      register: reset_result

    - name: Mostrar resultado final
      debug:
        msg: "Senha resetada com sucesso para o usuário '{{ target_user }}'"
