---
- name: Reset User Password on Active Directory
  hosts: domain_controller_group 
  gather_facts: false
  become: false 

  vars_prompt:
    # Estas variáveis serão preenchidas pelos usuários no AWX
    - name: "target_username"
      prompt: "Digite o nome de usuário (sAMAccountName) para resetar"
      private: no
    
    - name: "new_password"
      prompt: "Digite a nova senha temporária"
      private: yes # A senha digitada não será visível na tela

  tasks:
    - name: Check if the target user exists and reset password
      # Use o módulo win_ad_user para interagir com o Active Directory
      community.windows.win_ad_user:
        name: "{{ target_username }}"
        state: present
        # 'password' é o campo que define a nova senha
        password: "{{ new_password }}"
        # Define a senha para expirar, forçando o usuário a trocá-la no próximo logon
        password_never_expires: no
        password_not_changeable: no
        password_expires: yes
        
      # As credenciais para rodar esta tarefa no DC (Domain Admin) devem vir
      # da Credencial do Projeto/Job Template do AWX.
      delegate_to: "{{ inventory_hostname }}"

    - name: Inform the support user that the reset was successful
      ansible.builtin.debug:
        msg: "Senha do usuário '{{ target_username }}' resetada com sucesso. O usuário será forçado a trocar a senha no próximo logon."
