---
- name: Reset AD User Password
  hosts: AD
  gather_facts: no

  vars:
    ad_server: "{{ ad_server }}" 
    ad_domain: "{{ ad_domain }}"
    ad_user: "{{ ad_user }}"
    ad_password: "{{ ad_password }}"
    ad_ssl: "{{ ad_ssl | default(false) }}"

  vars_prompt:
    - name: target_user
      prompt: "Digite o username do AD a resetar"
      private: no

    - name: new_password
      prompt: "Digite a nova senha"
      private: yes

  tasks:
    - name: Reset password for user {{ target_user }}
      microsoft.ad.user:
        identity: "{{ target_user }}"
        password: "{{ new_password }}"
        update_password: always
        server: "{{ ad_server }}"
        domain_username: "{{ ad_user }}"
        domain_password: "{{ ad_password }}"
        ssl: "{{ ad_ssl }}"
        state: present
      register: reset_result

    - name: Mostrar resultado
      debug:
        msg: "Senha resetada com sucesso para o usuário {{ target_user }}"
