---
- name: Reset AD User Password
  hosts: AD
  gather_facts: no

  vars_prompt:
    - name: target_user
      prompt: "Digite o sAMAccountName"
      private: no
    - name: new_password
      prompt: "Digite a nova senha temporária"
      private: yes

  tasks:
    - name: 1. Buscar usuário no AD
      microsoft.ad.object_info:
        filter: "sAMAccountName -eq '{{ target_user }}'"
      register: ad_user_info

    - name: 2. Validar existência
      fail:
        msg: "ERRO: O usuário '{{ target_user }}' não foi encontrado."
      when: ad_user_info.objects | length == 0

    - name: 3. Reset password e forçar troca (Removendo 'Nunca Expira')
      microsoft.ad.user:
        identity: "{{ ad_user_info.objects[0].DistinguishedName }}"
        password: "{{ new_password }}"
        update_password: always
        password_never_expires: no   # Desmarca "A senha nunca expira"
        password_expired: yes         
        # ---------------------------
        account_locked: no
        state: present
      register: password_result

    - name: 4. Resultado Final
      debug:
        msg: "Sucesso! Senha de '{{ target_user }}' resetada e política de expiração atualizada."
      when: password_result.changed
    - name: 4. Resultado Final
      debug:
        msg: "Sucesso! Senha de '{{ target_user }}' resetada. O usuário deve trocar a senha no próximo login."
      when: password_result.changed
