---
- name: Reset AD User Password
  hosts: AD
  gather_facts: no

  vars_prompt:
    - name: target_user
      prompt: "Digite o username do AD a resetar (ex: d.garcia)"
      private: no

    - name: new_password
      prompt: "Digite a nova senha"
      private: yes

  tasks:

    - name: Verificar se o usuário existe no AD
      microsoft.ad.user:
        name: "{{ target_user }}"
        state: query
      register: user_check
      ignore_errors: yes

    - name: Falhar se o usuário não existir
      fail:
        msg: "O usuário '{{ target_user }}' não existe no Active Directory!"
      when: user_check is failed or user_check.found is not defined or user_check.found == 0

    - name: Reset password para o usuário {{ target_user }}
      microsoft.ad.user:
        name: "{{ target_user }}"
        password: "{{ new_password }}"
        update_password: always
        state: present
      register: reset_result

    - name: Mostrar resultado
      debug:
        msg: "Senha resetada com sucesso para o usuário '{{ target_user }}'"
