---
- name: Aplicar patch KB5033371 em servidores Windows
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Instalar patch KB5033371
      win_updates:
        category_names:
          - SecurityUpdates
        state: installed
        hotfix_id:
          - KB5033371
      register: update_result

    - name: Reiniciar se necessário
      win_reboot:
      when: update_result.reboot_required

    - name: Esperar que o servidor esteja de volta
      wait_for:
        port: 5985
        timeout: 600
      when: update_result.reboot_required

